// Training content in display order. Add a node file, import it, append it here.
import method from './method.js'
import loops from './loops.js'
import arraysInPlace from './arrays-in-place.js'
import grids from './grids.js'
import twoPointers from './two-pointers.js'
import strings from './strings.js'
import digitArrays from './digit-arrays.js'
import hashMaps from './hash-maps.js'
import frequency from './frequency.js'
import bits from './bits.js'
import sets from './sets.js'
import tracking from './tracking.js'
import stacks from './stacks.js'
import binarySearch from './binary-search.js'
import rotation from './rotation.js'
import merging from './merging.js'
import slidingWindow from './sliding-window.js'
import prefixSums from './prefix-sums.js'
import linkedLists from './linked-lists.js'
import trees from './trees.js'
import gridBfs from './grid-bfs.js'
import floodFill from './flood-fill.js'
import recursion from './recursion.js'
import graphs from './graphs.js'
import topoOrder from './topo-order.js'
import intervals from './intervals.js'
import heaps from './heaps.js'
import sorting from './sorting.js'
import enumeration from './enumeration.js'
import backtracking from './backtracking.js'
import greedy from './greedy.js'
import weightedGraphs from './weighted-graphs.js'
import unionFind from './union-find.js'
import dpLine from './dp-line.js'
import dpGrid from './dp-grid.js'
import dpChoices from './dp-choices.js'
import knapsackDp from './knapsack-dp.js'
import twoStrings from './two-strings.js'
import monotonic from './monotonic.js'
import caches from './caches.js'
import tries from './tries.js'
import stringSearch from './string-search.js'
import searchTheAnswer from './search-the-answer.js'
import intervalDp from './interval-dp.js'
export { TIERS } from '../../../training/progress.js'
export { TOOLS, TOOL_BY_ID } from './tools/index.js'

export const NODES = [method, loops, arraysInPlace, grids, twoPointers, strings, digitArrays, hashMaps, frequency, bits, sets, tracking, stacks, binarySearch, rotation, merging, slidingWindow, prefixSums, linkedLists, trees, gridBfs, floodFill, recursion, graphs, topoOrder, intervals, heaps, sorting, enumeration, backtracking, greedy, weightedGraphs, unionFind, dpLine, dpGrid, dpChoices, knapsackDp, twoStrings, monotonic, caches, tries, stringSearch, searchTheAnswer, intervalDp]
export const NODE_BY_ID = Object.fromEntries(NODES.map(n => [n.id, n]))
