// Gate content for the sql course. One object per gate; see CLAUDE.md for the voice and schema.
// The learner writes one SELECT statement per gate against the fixture in fixture.sql.
const g = (id, rank, xp, stat, title, algo, story, mission, hint, code) => ({ id, rank, xp, stat, title, algo, story, mission, hint, code });

const ARCS = [
{ name:'Arc I — The dump', sub:'Six tables off Halden\'s server, and a fence who will not read a spreadsheet.', gates:[
  g('pullnames','F',40,'filter','Names off the list','SELECT, WHERE, ORDER BY',
    ['The dump came out of Halden\'s server in six tables. The fence wants one thing first: who has vault access.',
     'Dax opens staff in a spreadsheet, sorts by department, and starts highlighting rows with the mouse. He misses one, then highlights a teller by mistake.',
     '“Ask the table,” Marguerite says. “It knows how to answer. Say which columns, say which rows, say what order. Three words and it is done.”'],
    'Return name and dept of every staff member in the vault department, alphabetical by name, as two columns named name and dept. Order matters. Stretch: make the same query work for a department name typed in any case.',
    'SELECT picks the columns, FROM names the table, WHERE keeps the rows you want, ORDER BY lines them up. Text goes in single quotes.',
`-- expected rows, in this order
('Ines Marr', 'vault')
('Kit Ferro', 'vault')
('Priya Nand', 'vault')`),
  g('bigmoves','F',45,'filter','The big moves','ORDER BY DESC, LIMIT',
    ['“The five biggest transfers,” the fence says. “Biggest first. I do not want the sixth.”',
     'Dax sorts the spreadsheet by amount, scrolls to the bottom because it sorted the wrong way, then screenshots a block of rows and counts them twice.',
     '“Sort, then take five,” Marguerite says. “Say both, in that order, and say which way is up.”'],
    'Return id and amount of the five largest transfers, largest first, as two columns named id and amount. Order matters. Stretch: the five smallest transfers that are still above 10,000.',
    'ORDER BY amount DESC puts the biggest on top. LIMIT 5 keeps the first five of whatever order you asked for, so the order clause has to come first in your head.'),
  g('nightdoors','F',45,'filter','Doors after dark','DISTINCT and ranges',
    ['Which doors opened after dark. The fence asks it like it is one question, and it is.',
     'Dax filters the badges spreadsheet to the late rows, then reads down the door column with his finger, saying each name and trying to remember if he has said it already.',
     '“Distinct is a word,” Marguerite says. “Use it. And the clock is text here, so ask for the time and compare it as text.”'],
    'Return each distinct door that was swiped at or after 22:00 or before 06:00, as one column named door, in any order. Stretch: add how many night swipes each door had.',
    'time(at) pulls the clock out of the timestamp as \'HH:MM:SS\', and text compares in order, so time(at) >= \'22:00\' works. Two conditions joined with OR, then DISTINCT on the column.',
`-- expected rows, any order
('lobby',)
('loading-bay',)
('server-room',)`),
  g('howmany','F',50,'shape','How many','COUNT with a filter',
    ['“How many personal accounts,” the fence says. Not which. How many.',
     'Dax filters the accounts spreadsheet to personal and counts the rows with his finger. He gets five, then four, then five.',
     '“The table can count,” Marguerite says. “Ask for one number, and give the number a name so she knows what she is looking at.”'],
    'Return one row with one column named n: how many accounts are of kind personal. Stretch: one row per kind, with its count.',
    'COUNT(*) counts the rows WHERE lets through. AS n names the column. One row comes back because there is one count.'),
]},
{ name:'Arc II — Who talks to whom', sub:'Six tables that only mean something when you put two of them side by side.', gates:[
  g('badgeowners','E',60,'join','Whose badge','INNER JOIN',
    ['The badge log is honest and useless: a staff id, a door, a time. The fence does not know who staff id 5 is, and she is not going to learn.',
     'Dax opens both sheets side by side and starts typing names into the badge rows by hand. Eleven rows in, he types the wrong one.',
     '“Two tables, one wire between them,” Marguerite says. “The badge carries a staff id. The staff table is keyed by that id. Say so, once, and the names arrive.”'],
    'Return every badge swipe with the staff member\'s name: three columns named name, door and at, any order. Stretch: keep only the swipes that went in.',
    'JOIN staff ON staff.id = badges.staff_id. Give each table a short alias so you can say which id you mean; a swipe whose staff id matches nobody drops out, which is what INNER means.',
`-- three of the seventeen rows
('Ines Marr', 'vault', '2026-03-02 08:55')
('Tomas Reed', 'lobby', '2026-03-02 07:30')
('Otto Kline', 'server-room', '2026-03-02 23:15')`),
  g('emptyaccounts','E',70,'join','Accounts nobody touched','LEFT JOIN … IS NULL',
    ['“Three of these accounts have never moved a penny,” the fence says. “Those are the ones I want. Nobody watches a dead account.”',
     'Dax looks for them by reading the transfer sheet and crossing account numbers off a list on the back of his hand. He crosses one off twice and misses another.',
     '“Keep every account, wire the transfers on beside them, then keep the ones where nothing arrived,” Marguerite says. “The empty seat is the answer.”'],
    'Return every account that has never sent and never received a transfer: two columns named id and holder, any order. Stretch: the same for accounts that have never sent but have received.',
    'A LEFT JOIN keeps every row on the left even when the right side has nothing to offer, filling the gap with blanks; then WHERE the right side IS NULL keeps only the gaps. Match on either end of the transfer.'),
  g('chainofcommand','D',90,'join','Who reports to whom','Self join',
    ['The staff table points at itself: every row carries the id of the person above it. One row points at nobody.',
     'Dax draws the tree on the back of a takeaway menu, gets two branches crossed, and declares that the head of security reports to a teller.',
     '“The table meets itself,” Marguerite says. “Two copies, two names, one wire between them. Call one of them the manager and the answer reads like a sentence.”'],
    'Return every staff member who has a manager, beside that manager\'s name: two columns named name and manager, alphabetical by name. Order matters. Stretch: include the one with no manager, showing the word none instead.',
    'JOIN staff m ON m.id = s.manager_id, with s and m two aliases for the same table. The person at the top has no manager id, so this join quietly leaves them out.',
`-- the first three of eleven rows
('Ana Petrov', 'Ruth Ash')
('Bo Lund', 'Tomas Reed')
('Ines Marr', 'Halden Voss')`),
  g('threeway','D',100,'join','Both ends of the wire','Two joins with aliases',
    ['A transfer row has two account numbers on it and no names at all. The fence wants both ends spelled out.',
     'Dax says he will just look each number up as he goes. Fourteen rows, twenty-eight lookups, and he is already asking what account 9 was.',
     '“Same table, twice, two different jobs,” Marguerite says. “One copy is the sender, one is the receiver. Name them that and stop thinking about it.”'],
    'Return every transfer with both holders\' names: four columns named id, sender, receiver and amount, ordered by id. Order matters. Stretch: only the transfers where both ends sit in the same branch.',
    'Join accounts twice under two aliases, one on from_acct and one on to_acct, and alias the two holder columns apart. Nothing is dropped: every transfer points at real accounts.'),
]},
{ name:'Arc III — The totals', sub:'The fence stops asking which and starts asking how much.', gates:[
  g('perdept','D',90,'shape','Heads per department','GROUP BY and COUNT',
    ['“How many bodies in each department,” the fence says. “Not names. Headcount. I am pricing a bribe, not writing a birthday card.”',
     'Dax sorts the staff sheet by department and counts each block with his finger, out loud, twice, getting two different numbers for security.',
     '“Pile them up,” Marguerite says. “One pile per department, and the answer is how tall each pile is. One of them has no department written down at all — leave that one out.”'],
    'Return one row per department with its headcount: two columns named dept and n, any order, skipping the staff member whose department was never written down. Stretch: order the answer by headcount, biggest first.',
    'GROUP BY dept makes one pile per value, COUNT(*) measures a pile, AS n names the number. A blank department is its own pile unless WHERE drops it first.'),
  g('heavyhitters','C',120,'shape','The heavy hitters','SUM and HAVING',
    ['“Which accounts are moving real money out,” the fence says. “Over half a million, all told. I do not care about a hundred small ones.”',
     'Dax adds up the amounts per account in his head, announces a number ending in three zeroes, and admits he might have counted a row twice.',
     '“Add up each pile, then sieve the piles,” Marguerite says. “WHERE thins the rows before the piles exist. What you want is the other sieve, the one that runs after.”'],
    'Return every account whose transfers out add up to more than 500,000: two columns named from_acct and total, largest total first. Order matters. Stretch: the same list by money received instead.',
    'GROUP BY from_acct, SUM(amount) AS total, then HAVING SUM(amount) > 500000. HAVING sieves piles; WHERE would be looking at single transfers, which is a different question.'),
  g('busiestdoor','C',130,'shape','The busiest door','GROUP BY, ORDER BY count, LIMIT 1',
    ['“One door,” the fence says. “The one that opens most. That is where I want the crew standing, because nobody looks twice at a busy door.”',
     'Dax counts the door column by eye, gets lobby and loading-bay within one of each other, and asks whether it really matters which.',
     '“Pile them up, sort the piles by height, take the top one,” Marguerite says. “Three clauses in a row and the question stops being an argument.”'],
    'Return one row: the door with the most swipes and how many it had, as two columns named door and n. Stretch: the quietest door instead.',
    'Count per door with GROUP BY, then ORDER BY that count descending and LIMIT 1. You may order by the name you gave the count.'),
  g('byday','C',140,'shape','Day by day','date() and GROUP BY',
    ['The transfer times carry a date and a clock. The fence wants a shape: which day was busy, which was quiet.',
     'Dax types the six dates down the side of a page by hand and tallies them, then finds a seventh he had not noticed.',
     '“The timestamp is text with a date hiding at the front,” Marguerite says. “Cut the date out and pile up by that. Never by the whole timestamp — no two of those are the same.”'],
    'Return how many transfers happened on each day: two columns named day and n, where day looks like 2026-03-02, earliest day first. Order matters. Stretch: the total moved on each day instead of the count.',
    'date(at) trims a timestamp down to its date. Group by that same expression, not by at, or every row becomes its own pile.'),
]},
{ name:'Arc IV — Inside the question', sub:'Some answers need a second question answered first, in the same breath.', gates:[
  g('abovemean','C',120,'filter','Above the average','Scalar subquery',
    ['“Anything unusual,” the fence says. “Bigger than normal. You work out what normal is — that is what I am paying for.”',
     'Dax averages the amounts on a calculator, writes 426250 on the back of his hand, and starts comparing rows to a number that will be wrong the moment another transfer lands.',
     '“Put the question inside the question,” Marguerite says. “The table works out its own average while it is looking, and the answer is still right tomorrow.”'],
    'Return every transfer larger than the average transfer amount: two columns named id and amount, largest first. Order matters. Stretch: transfers larger than the average for their own sending account.',
    'A SELECT that returns one row and one column can stand where a number stands: WHERE amount > (SELECT AVG(amount) FROM transfers). The brackets are not optional.'),
  g('neverswiped','B',160,'filter','Never swiped in','NOT EXISTS',
    ['Twelve people on the staff list. Seventeen swipes in the badge log, and not one of them belongs to two of those people.',
     'Dax ticks names off the staff sheet as he reads the badge log, loses his place somewhere around the fourth vault entry, and starts again.',
     '“Ask the badge log a yes-or-no question about each person, then keep the people it says no to,” Marguerite says. “One of them never comes in. That is the one who matters.”'],
    'Return every staff member with no badge swipe at all: two columns named id and name, by id. Order matters. Stretch: the same for staff who swiped in but never out.',
    'NOT EXISTS (SELECT 1 FROM badges b WHERE b.staff_id = s.id) asks the badge log about the row you are standing on. The inner SELECT list is ignored, so 1 is the polite thing to put there.'),
  g('bucket','B',170,'filter','Small, medium, large','CASE',
    ['“I do not want fourteen numbers,” the fence says. “I want to know which are small, which are worth reading, and which are the reason we are all here.”',
     'Dax colours the spreadsheet rows in three shades of highlighter. The photocopy comes out grey.',
     '“Write the band into the row,” Marguerite says. “The table can label its own rows, and a word survives a photocopier.”'],
    'Return every transfer with a band: three columns named id, amount and band, where band is small below 50,000, medium below 500,000 and large otherwise, ordered by id. Order matters. Stretch: how many transfers fall in each band.',
    'CASE WHEN … THEN … WHEN … THEN … ELSE … END is one column, so give it a name with AS. The first WHEN that fits wins, so write the bands in order.'),
  g('twolists','B',180,'join','Two lists, one answer','UNION and EXCEPT',
    ['The Ledger has two name columns: who paid and who was paid. The fence wants one list of everybody it touches.',
     'Dax copies both columns into one, sorts it, and spends ten minutes deleting the names that now appear twice.',
     '“Stack one list on the other and the repeats fall away by themselves,” Marguerite says. “There is a version that keeps them, and we do not want it.”'],
    'Return every name that appears anywhere in the payments table, as payer or as payee, once each: one column named name, any order. Stretch: the payers who were never paid.',
    'Two SELECTs with UNION between them stack into one list and drop the repeats; UNION ALL keeps them. The column name of the answer comes from the first SELECT.'),
]},
{ name:'Arc V — The Books', sub:'The last four questions, and then the fence closes the book.', gates:[
  g('runningtotal','A',200,'shape','The running total','Window aggregate',
    ['“I want to see it build,” the fence says. “Payment by payment, with the total so far beside each one. That is how you spot the month somebody got greedy.”',
     'Dax says he can do that: one column of numbers, one column where each cell adds the one above. It takes him eleven cells to make an error, and the error compounds.',
     '“Every row keeps its own line and gets the total so far beside it,” Marguerite says. “The table can look back along the order you gave it without folding the rows together.”'],
    'Return every payment with the total so far: three columns named paid_on, amount and running, ordered by paid_on and then by id, where running is every payment up to and including that row added together. Order matters. Stretch: the same, restarted for each payer.',
    'SUM(amount) OVER (ORDER BY paid_on, id) adds up everything from the first row to this one. It sits in the SELECT list beside the ordinary columns, and no rows are folded together.'),
  g('toppercamera','A',220,'shape','Top per floor','ROW_NUMBER over a partition',
    ['“The newest camera on each floor,” the fence says. “The new ones record to somewhere I cannot reach.”',
     'Dax sorts the camera sheet by floor, then by date, then reads off the wrong row on two of the four floors because he forgot which way the dates ran.',
     '“Number the cameras within each floor, newest first, then keep the ones numbered one,” Marguerite says. “Four floors, four answers, no arguing.”'],
    'Return the newest camera on each floor: three columns named floor, zone and installed, one row per floor, by floor. Order matters. Stretch: the two newest per floor.',
    'ROW_NUMBER() OVER (PARTITION BY floor ORDER BY installed DESC) numbers each floor\'s cameras separately. You cannot sieve on that number in the same SELECT, so wrap the whole thing and filter outside.'),
  g('reportsto','A',240,'join','Climb the chain','Recursive CTE',
    ['Ana Petrov signs for the loading bay at ten at night. The fence wants to know who she answers to, and who they answer to, all the way up.',
     'Dax follows the manager ids by hand, one lookup at a time, and gets to the top by luck. He cannot tell you how many steps it took.',
     '“Climb the chain,” Marguerite says. “Start at her, take one step up, then take one step up from wherever you got to, and keep going until there is nowhere to step.”'],
    'Return everyone above Ana Petrov, who is staff id 12: two columns named name and level, where her manager is level 1, that manager\'s manager is level 2, and so on, lowest level first. Order matters. Stretch: the same chain for any staff id, and the length of the longest chain in the table.',
    'WITH RECURSIVE up(...) AS (a starting row UNION ALL a SELECT that joins staff back onto up), then SELECT from up. Start at id 12 with level 0 and leave that row out of the answer.'),
  g('thebooks','S',320,'shape','The Books','Combining the pieces',
    ['The fence puts the book on the table and turns it round. “Last question. Who did Halden pay, how much in all, who took the most, and which of them are worth talking to.”',
     'Dax looks at the four things in that sentence, then at the spreadsheet, then at the door.',
     '“Name the totals first, then read them back with a place and a band,” Marguerite says. “Four questions, one answer, one statement. Then we are done here.”'],
    'Return one row per payee: four columns named payee, total, place and band, where total is everything that payee received, place is 1 for the largest total with ties broken by payee name alphabetically, and band is big from 100,000 up, middling from 25,000 up and small below, ordered by place. Order matters. Stretch: add each payee\'s share of everything paid, rounded to two decimals.',
    'WITH totals AS (…GROUP BY payee…) names the piles first. Then read totals back, put ROW_NUMBER() OVER (ORDER BY total DESC, payee) beside each row, and label it with CASE.'),
]},
];
export const ARCS_DATA = ARCS;
